"""
gen_win16_stubs.py - Emit the Win16 import surface for DANCE02.DLL.

Writes two files from the NE's own relocations, so the shim layer can never
drift from what the binary actually imports:

  runtime/runtime_api.h        prototypes for every import, plus the indirect
                               dispatchers and the INT handlers
  runtime/win16/win16_stubs.c  a default body for every import NOT hand-written
                               in another runtime/win16/*.c

The contract every shim obeys, hand-written or generated:

    ne_lift emits  push16(cs); push16(ret_off); MODULE_API(cpu);

  so the shim pops 4 bytes of far return address plus its PASCAL argument
  purge (win16.PURGE), returns WORD in AX and DWORD in DX:AX, and returns
  normally - there is no RETF to execute, the C return IS the RETF.

Regenerate after changing win16.py or the target binary:
    python tools/gen_win16_stubs.py
"""
import os
import re
import sys
import glob

sys.path.insert(0, os.path.dirname(__file__))
from ne_parse import parse_ne
import win16

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
DLL = os.path.join(ROOT, 'work', 'DANCE02.DLL')
API_H = os.path.join(ROOT, 'runtime', 'runtime_api.h')
STUBS = os.path.join(ROOT, 'runtime', 'win16', 'win16_stubs.c')

# A hand-written shim is any `void MODULE_API(CPU *cpu)` definition in
# runtime/win16/ other than the generated stub file itself.
DEF_RE = re.compile(r'^void ([A-Z0-9_]+)\(CPU \*cpu\)', re.M)


def imports_used(ne):
    """Every distinct import the binary's relocations actually reference."""
    seen = {}
    for seg in ne.segments:
        for r in seg.relocations:
            if (r.flags & 3) not in (1, 2):
                continue
            mod = win16.module_name(ne, r.module_idx)
            imp = win16.get_import(mod, r.ordinal)
            # OFFSET16 imports are absolute values patched into the code
            # stream (__AHSHIFT, __AHINCR, __WINFLAGS), never called.
            entry = seen.setdefault(imp.name, [imp, False])
            if r.src_type != 5:
                entry[1] = True
    return seen


def hand_written():
    names = set()
    for path in glob.glob(os.path.join(ROOT, 'runtime', 'win16', '*.c')):
        if os.path.abspath(path) == os.path.abspath(STUBS):
            continue
        names.update(DEF_RE.findall(
            open(path, encoding='utf-8', errors='replace').read()))
    return names


def main():
    ne = parse_ne(DLL)
    used = imports_used(ne)
    have = hand_written()

    by_mod = {}
    for name, (imp, called) in used.items():
        by_mod.setdefault(imp.module, []).append((name, imp, called))

    # ---- runtime_api.h ----
    h = ['/* runtime_api.h - Auto-generated by gen_win16_stubs.py. Do not edit. */',
         '/* Host entry points the lifted DANCE02 code calls: indirect-call     */',
         '/* dispatchers, INT handlers, and the Win16 import shims.             */',
         '#ifndef EJAY_RUNTIME_API_H',
         '#define EJAY_RUNTIME_API_H',
         '',
         '#include "cpu.h"',
         '',
         '/* ---- Indirect call dispatchers (function pointers) ---- */',
         'void dispatch_far(CPU *cpu, uint16_t seg, uint16_t off);',
         'void dispatch_near(CPU *cpu, uint16_t seg, uint16_t off);',
         '',
         '/* ---- Software interrupts ---- */',
         'void int_handler(CPU *cpu, int int_num);',
         'void dos_int21(CPU *cpu);',
         '',
         f'/* ---- Win16 import shims ({len(used)} total) ---- */']
    for mod in sorted(by_mod):
        entries = sorted(by_mod[mod])
        h.append('')
        h.append(f'/* {mod} ({len(entries)}) */')
        for name, imp, called in entries:
            purge = win16.get_purge(imp.module, imp.api)
            kind = f'purge {purge}' if called else 'absolute value, not called'
            h.append(f'void {name}(CPU *cpu);  /* @{imp.ordinal} {imp.api}, {kind} */')
    h += ['', '#endif /* EJAY_RUNTIME_API_H */']
    os.makedirs(os.path.dirname(API_H), exist_ok=True)
    with open(API_H, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(h) + '\n')

    # ---- win16_stubs.c ----
    c = ['/* win16_stubs.c - Auto-generated by gen_win16_stubs.py. Do not edit. */',
         '/* Default body for every import with no hand-written shim: purge the */',
         '/* frame correctly, return 0, and say so once so an unimplemented call */',
         '/* announces itself instead of silently returning garbage.            */',
         '',
         '#include <stdio.h>',
         '#include "cpu.h"',
         '#include "runtime_api.h"',
         '',
         'static void unimpl(CPU *cpu, const char *api, int purge)',
         '{',
         '    static const char *seen[256];',
         '    static int nseen;',
         '    int i;',
         '    for (i = 0; i < nseen; i++)',
         '        if (seen[i] == api) break;',
         '    if (i == nseen && nseen < 256) {',
         '        seen[nseen++] = api;',
         '        fprintf(stderr, "[win16] unimplemented: %s\\n", api);',
         '    }',
         '    cpu->ax = 0; cpu->dx = 0;',
         '    cpu->sp = (uint16_t)(cpu->sp + 4 + purge);   /* far retaddr + PASCAL args */',
         '}',
         '']
    generated = 0
    for mod in sorted(by_mod):
        for name, imp, called in sorted(by_mod[mod]):
            if name in have:
                continue
            if not called:
                # Absolute-value import: nothing ever calls it. Emit a body that
                # traps rather than one that silently unwinds a frame.
                msg = f'[win16] {imp.api} called, but it is an absolute value import'
                c.append(f'void {name}(CPU *cpu) {{ (void)cpu; '
                         f'fprintf(stderr, "{msg}\\n"); }}')
                generated += 1
                continue
            purge = win16.get_purge(imp.module, imp.api)
            c.append(f'void {name}(CPU *cpu) {{ unimpl(cpu, "{imp.module}.{imp.api}", {purge}); }}')
            generated += 1
    c.append('')
    os.makedirs(os.path.dirname(STUBS), exist_ok=True)
    with open(STUBS, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(c) + '\n')

    print(f'Wrote {API_H}: {len(used)} imports across {len(by_mod)} modules')
    print(f'Wrote {STUBS}: {generated} generated, {len(used) - generated} hand-written')
    for mod in sorted(by_mod):
        n = len(by_mod[mod])
        hw = sum(1 for name, _, _ in by_mod[mod] if name in have)
        print(f'  {mod:<10s} {n:3d}  ({hw} hand-written)')


if __name__ == '__main__':
    main()
