"""
gen_exports.py - Emit runtime/exports.h: DANCE02's 34 entry points by name.

The NE entry table plus the resident/non-resident name tables give every export
its real name and its (segment, offset). Those names are the author's own -
AInit, AStart, APlay, ALautSet, ABilder, AWaveDauer - so the harness can call
the engine in its own vocabulary instead of by address.

    python tools/gen_exports.py
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))
from ne_parse import parse_ne

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
DLL = os.path.join(ROOT, 'work', 'DANCE02.DLL')
OUT = os.path.join(ROOT, 'runtime', 'exports.h')


def main():
    ne = parse_ne(DLL)

    # ne_parse already joins the entry table to both name tables, so every
    # exported entry arrives carrying the name its author gave it.
    rows = sorted((e.ordinal, e.name, e.segment, e.offset)
                  for e in ne.entries if e.name)

    # An entry point the lifter could not align to an instruction boundary has
    # no lifted function behind it. Emit NULL rather than an undefined symbol,
    # so the link succeeds and the harness can report the gap honestly.
    lifted = set()
    src_dir = os.path.join(ROOT, 'src')
    if os.path.isdir(src_dir):
        for fn in os.listdir(src_dir):
            if fn.endswith('.c'):
                lifted.update(re.findall(
                    r'^void (seg\d+_[0-9A-Fa-f]+)\(CPU \*cpu\)',
                    open(os.path.join(src_dir, fn), encoding='utf-8',
                         errors='replace').read(), re.M))

    lines = [
        '/* exports.h - Auto-generated by gen_exports.py. Do not edit. */',
        '/* DANCE02.DLL entry points, with the names its author gave them. */',
        '#ifndef EJAY_EXPORTS_H',
        '#define EJAY_EXPORTS_H',
        '',
        '#include "segments.h"',
        '',
        'typedef struct { const char *name; int ordinal; void (*fn)(CPU *); } EjayExport;',
        '',
        f'#define EJAY_NUM_EXPORTS {len(rows)}',
        'static const EjayExport EJAY_EXPORTS[] = {',
    ]
    missing = 0
    for ordinal, name, seg, off in rows:
        sym = f'seg{seg:03d}_{off:04X}'
        if sym in lifted:
            lines.append(f'    {{ "{name}", {ordinal}, {sym} }},')
        else:
            missing += 1
            lines.append(f'    {{ "{name}", {ordinal}, 0 }},   /* {sym} not lifted */')
    lines += ['};', '', '#endif /* EJAY_EXPORTS_H */']

    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'Wrote {OUT}: {len(rows)} named exports'
          + (f', {missing} with no lifted function' if missing else ''))
    for ordinal, name, seg, off in rows:
        sym = f'seg{seg:03d}_{off:04X}'
        mark = '' if sym in lifted else '   <-- not lifted'
        print(f'  @{ordinal:<3d} {name:<16s} seg{seg}:{off:04X}{mark}')


if __name__ == '__main__':
    main()
